//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public PhoneNumber()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public string TelephoneNumber { get; set; }
        public string Owner { get; set; }
        public System.DateTime lastStatusChange { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
