//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int PhoneNumberTableId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
    
        public virtual PhoneNumber PhoneNumber { get; set; }
    }
}
